wrapperUrl=https://repo1.maven.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.3.2/maven-wrapper-3.3.2.jar
distributionUrl=https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip
distributionSha256Sum=6b1bd4f5e3b9fc6a8808186b5ae65afc35d41c353ee7f7e5b377b10247f5e4e1
wrapperVersion=3.3.2
