spring.datasource.url=jdbc:postgresql://${PGSQL_HOST:localhost}:${PGSQL_PORT:5432}/${PGSQL_DATABASE:logdb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${PGSQL_USER:loguser}
spring.datasource.password=${PGSQL_PASSWORD:logpass}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
